### ISSUE TITLE
Add ignored patterns

### ISSUE THREAD

**Issue by laike9m** [7kfpun/atom-pangu#1]
我用 markdown 写作时，`**你好**` 会被 pangu 插件变成 `** 你好 **`，于是粗体效果就没了。是否能够增加一个 filter，让用户可以自定义在和某些字符相邻时候不增加空格？

**Comment by laike9m** [comment]
相信这个问题会有蛮多人遇到的

**Comment by 7kfpun** [comment]
同意，畢竟自動加空格後，要人手刪除不必要的空格顯得很愚蠢。
但是 Markdown 並不是“正常”文章，HTML 也一樣，要為這些“文章”加 filter 恐怕花很多時間，
加上自定義又會產生無限的 settings。。。讓我想想怎麼搞。。。

所以先更新了 0.2.0，這個版本支持只加空格在選起的字段，這樣能減少很多手動程序了。

**Comment by laike9m** [comment]
可能我没表述清楚。我的意思是能否增加一个通用的选项，这个选项里可以由用户去填在什么情况下空格不会被添加，并不需要专门针对 markdown 或者 HTML 来做。

**Comment by 7kfpun** [comment]
嗯，大概清楚。你先更新 0.2.0 版本，先撐著用吧，應該沒那麼快寫好 :laughing:

**Comment by laike9m** [comment]
大神加油！

**Comment by 7kfpun** [comment]
Done!

**Comment by yisibl** [comment]
在 markdown 中，忽略 `**` 这个最终应该在 ignored patterns 中设置什么选项？
