### ISSUE TITLE
有些空格会被自动删除

### ISSUE THREAD

**Issue by bingohuang** [7kfpun/atom-pangu#2]
你好，pangu插件的核心是在中文和英文间插入空格，功能实用，省时省力，赞一下作者。
但我发现，该插件还会删除文档中的一些希望保留的空格，这使我措手不及，举例如下：

``` go
-   ErrUnmatchedLpar = errors.New("regexp: unmatched '('")
+   ErrUnmatchedLpar = errors.New("regexp: unmatched'('")
```

将 `unmatched`和单引号之间的空格自动去掉了
还比如：

```
-       term [ '*' | '+' | '?' ]
+       term [ '*'|'+'|'?' ]
```

将各个标点符号之前的空格都删去了，反而有些影响文档的阅读格式。

有些空格我不希望删除，虽然有正则表达式的模式配置，但毕竟配置起来会略麻烦，请作者看看，是否有更好的解决方式？比如对这种完全是英文文档中标点间的空格，就自动不做处理了。

**Comment by 7kfpun** [comment]
你好 @bingohuang ，

這插件原意在“正常”文章中使用，不適用在程式碼。要不加個 “skip_no_CJK_line” 配置？

**Comment by bingohuang** [comment]
原来如此。如果能加上，就太赞了，因为在一般的计算机文档或书籍中，避免不了会有很多程序代码的引用呢。
请问“ skip_no_CJK_line”配置是如何加的？pangu的setting中，还是需要你在代码中加上？

**Comment by 7kfpun** [comment]
這插件支持只在選擇的字段處理，你可以用用看。

“skip_no_CJK_line” 放在代碼吧，等下試試。

**Comment by 7kfpun** [comment]
Done! 歡迎更多建議！

**Comment by bingohuang** [comment]
速度真快！
但是出现了一个始料未及的问题，就是我升级了pangu插件之后，atom中反而加载不出来了（甚至其他一些插件同样加载不出来）。
我的环境如下：

```
Mac OS X
Atom 1.9.6
```

我本地测试了几遍，现象就是：

```
apm link pangu 导致插件加载失败
apm unlink pangu 其他插件就加载成功了
```

还请 @7kfpun 确认

**Comment by 7kfpun** [comment]
可否幫我刪除再裝載嗎？不好意思浪費你時間了... 剛剛才去了 guest mode 試，沒發現問題...

```
apm rm pangu
apm install pangu
```

**Comment by bingohuang** [comment]
嗯，因为我这边apm的网络很慢，基本很难通过`apm install pangu`安装上，我是通过git下载的方式安装`git clone https://github.com/7kfpun/atom-pangu.git ~/.atom/packages/pangu`
测试了两遍，表现还是如此：安装上pangu后，其他Community Package就加载失败（包括pangu自身），卸载pangu之后，就好了，很是怪异啊。

**Comment by 7kfpun** [comment]
噢，我知道了，我的錯，你有 npm 吧。謝謝你了！

`cd ~/.atom/packages/pangu && npm install`

**Comment by bingohuang** [comment]
@7kfpun 加上npm install，现在安装没问题了，感谢。
但是好像出现了一个bug：在英文处会被重复复制，如下

```
case *bool:
    fmt.Printf("pointer to boolean %t\n", *t) // t has type *bool
```

pangu spacing之后编程

```
case *bool:*case *bool:
    fmt.Printf("pointer to boolean %t\n", *t) // t has type *bool*  fmt.Printf("pointer to boolean %t\n", *t) // t has type *bool*  fmt.Printf("pointer to boolean %t\n", *t) // t has type *bool
```

**Comment by 7kfpun** [comment]
我測試了，都正常。你是裝了 0.5.0 版本嗎？

**Comment by bingohuang** [comment]
我是装了0.5.0版本，截图截图如下：
![snip20160812_32](https://cloud.githubusercontent.com/assets/3715340/17613208/5ea4780e-608d-11e6-9f4e-86a523a4e5ad.png)

但是在正文中运行pangu spacing，确实会出现英文被重复书写的情况，比如：
原文

``` go
err := http.ListenAndServe(*addr, nil)
```

pangu spacing之后：

``` go
err := http.ListenAndServe(*addr, nil)*    err := http.ListenAndServe(*addr, nil)
```

**Comment by bingohuang** [comment]
哦，终于明白了，我因为设置了：`Ignoring text with the matched pattern`为 `\*`，导致了这个问题的出现。去掉这个设置之后，就正常了。是否说明这两个设置间有冲突？

**Comment by 7kfpun** [comment]
嗯，Ignoring text with the matched pattern 那裡有 bug，謝謝了。

**Comment by bingohuang** [comment]
不客气，这个插件还是很好用的，期待越做越好！ 😃
